import type { Metadata } from "next";
import HeaderTable from "@/components/headertable";

import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <head>
        <title>My Todo App</title>
      </head>
      <body className="min-h-full flex flex-col">
        <HeaderTable />
        {children}</body>
    </html>
  );
}
